env:
  browser: true
  commonjs: true
  es2021: true
extends: airbnb-base
parserOptions:
  ecmaVersion: latest
rules:
  global-require: off
  no-plusplus: off
  no-console: off
  import/no-dynamic-require: off

